//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace royalcatbreed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cats_front_page
    {
        public int id { get; set; }
        public string foto { get; set; }
        public string cat_name { get; set; }
        public string cat_text { get; set; }
        public string personality { get; set; }
        public string history { get; set; }
        public string body { get; set; }
        public string legs_paws { get; set; }
        public string head { get; set; }
        public string coat { get; set; }
        public string ears { get; set; }
        public string color { get; set; }
        public string eyes { get; set; }
        public string tail { get; set; }
        public string disclaimer { get; set; }
        public int playfulness { get; set; }
        public int atcivity_level { get; set; }
        public int friendliness_others { get; set; }
        public int friendliness_children { get; set; }
        public int grooming_req { get; set; }
        public int vocality { get; set; }
        public int need_for_attn { get; set; }
        public int affection { get; set; }
        public int docility { get; set; }
        public int intelligence { get; set; }
        public int independence { get; set; }
        public int hardiness { get; set; }
        public string cat_problems { get; set; }
        public string cat_nutrition { get; set; }
        public string cat_behavior_training { get; set; }
        public string cat_grooming { get; set; }
        public string home_instructions { get; set; }
    }
}
